[package]
name = "rendertoy"
version = "0.1.0"
authors = ["Tomasz Stachowiak"]
edition = "2018"

[dependencies]
failure = "0.1.3"
snoozy = { git = "https://github.com/h3r2tic/snoozy" }
#snoozy = { path = "../snoozy" }
shader-prepper = "0.2.0"
regex = "1.0.6"
notify = "4.0.0"
lazy_static = "1.2.0"
obj-rs = "0.4"
serde = "1.0.80"
serde_derive = "1.0.80"
bincode = "1.0.1"
glutin = "0.19.0"
gl = "*"
image = "0.20.1"
relative-path = "0.4.0"
cargo = "0.32.0"
clap = "2.32.0"
nalgebra = { version = "0.17",  features = ["serde-serialize"] }
libflate = "0.1.19"
typemap = "0.3.3"
